name: wp-pager

services:
    app:
        image: wp-pager-app
        build: .
        container_name: wp-pager-app
        restart: always
        ports:
            - 8080:80
        depends_on:
            - db
        networks:
            - database
        volumes:
            - ./wordpress:/var/www/html:Z
            - ./plugin:/var/www/html/wp-content/plugins/wp-pager:Z
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: pager
            WORDPRESS_DB_PASSWORD: 111111
            WORDPRESS_DB_NAME: pager
            WORDPRESS_DEBUG: 1

    db:
        image: mariadb:10.7.3-focal
        command: --default-authentication-plugin=mysql_native_password
        container_name: wp-pager-db
        restart: always
        ports:
            - 2222:3306
        networks:
            - database
        volumes:
            - db_data:/var/lib/mysql:Z
        environment:
            MYSQL_DATABASE: pager
            MYSQL_USER: pager
            MYSQL_PASSWORD: 111111
            MYSQL_ROOT_PASSWORD: 111111

volumes:
    db_data:

networks:
    database:
        driver: bridge
